export const ADMIN_FETCH_USER_STARTED = 'ADMIN_FETCH_USER_STARTED';
export const ADMIN_FETCH_USER_SUCCESSED = 'ADMIN_FETCH_USER_SUCCESSED';
export const ADMIN_FETCH_USER_FAILURED = 'ADMIN_FETCH_USER_FAILURED';