export const ADMIN_FETCH_FAA_STARTED = 'ADMIN_FETCH_FAA_STARTED';
export const ADMIN_FETCH_FAA_SUCCESSED = 'ADMIN_FETCH_FAA_SUCCESSED';
export const ADMIN_FETCH_FAA_FAILURED = 'ADMIN_FETCH_FAA_FAILURED';