export const ADMIN_FETCH_GROUP_STARTED = 'ADMIN_FETCH_GROUP_STARTED';
export const ADMIN_FETCH_GROUP_SUCCESSED = 'ADMIN_FETCH_GROUP_SUCCESSED';
export const ADMIN_FETCH_GROUP_FAILURED = 'ADMIN_FETCH_GROUP_FAILURED';