export const ADMIN_FETCH_POST_STARTED = 'ADMIN_FETCH_POST_STARTED';
export const ADMIN_FETCH_POST_SUCCESSED = 'ADMIN_FETCH_POST_SUCCESSED';
export const ADMIN_FETCH_POST_FAILURED = 'ADMIN_FETCH_POST_FAILURED';