export const ADMIN_DASHBOARD_FETCH_STARTED = 'ADMIN_DASHBOARD_FETCH_STARTED';
export const ADMIN_DASHBOARD_FETCH_SUCCESSED = 'ADMIN_DASHBOARD_FETCH_SUCCESSED';
export const ADMIN_DASHBOARD_FETCH_FAILURED = 'ADMIN_DASHBOARD_FETCH_FAILURED';