export const ADMIN_FETCH_REPORT_STARTED = 'ADMIN_FETCH_REPORT_STARTED';
export const ADMIN_FETCH_REPORT_SUCCESSED = 'ADMIN_FETCH_REPORT_SUCCESSED';
export const ADMIN_FETCH_REPORT_FAILURED = 'ADMIN_FETCH_REPORT_FAILURED';