export const FETCH_ALBUM_STARTED = 'FETCH_ALBUM_STARTED';
export const FETCH_ALBUM_SUCCEEDED = 'FETCH_ALBUM_SUCCEEDED'
export const FETCH_ALBUM_FAILED = 'FETCH_ALBUM_FAILED'

export const CREATE_ALBUM = 'CREATE_ALBUM'