export const FETCH_COMMENT_POST_STARTED = 'FETCH_COMMENT_POST_STARTED'
export const FETCH_COMMENT_POST_SUCCEEDED = 'FETCH_COMMENT_POST_SUCCEEDED'
export const FETCH_COMMENT_POST_FAILED = 'FETCH_COMMENT_POST_FAILED'
export const CREATE_COMMENT = 'CREATE_COMMENT'