export const FETCH_GROUP_STARTED = 'FETCH_GROUP_STARTED'
export const FETCH_GROUP_SUCCEEDED = 'FETCH_GROUP_SUCCEEDED'
export const FETCH_GROUP_FAILED = 'FETCH_GROUP_FAILED'

export const CREATE_GROUP = 'CREATE_GROUP'