export const FETCH_POSTHISTORY_STARTED = 'FETCH_POSTHISTORY_STARTED';
export const FETCH_POSTHISTORY_SUCCEEDED = 'FETCH_POSTHISTORY_SUCCEEDED';
export const FETCH_POSTHISTORY_FAILED = 'FETCH_POSTHISTORY_FAILED';