export const FETCH_POST_STARTED = 'FETCH_POST_STARTED'
export const FETCH_POST_SUCCEEDED = 'FETCH_POST_SUCCEEDED'
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED'

export const ADD_POST_SUCCEEDED = 'ADD_POST_SUCCEEDED'
export const ADD_POST_FAILED = 'ADD_POST_FAILED'
export const ADD_POST = 'ADD_POST'