export const FETCH_USER_STARTED = 'FECT_USER_STARTED';
export const FETCH_USER_SUCCESSED = 'FECT_USER_SUCCESSED';
export const FETCH_USER_FAILED = 'FECT_USER_FAILED';

export const UPDATE_USER_STARTED = 'UPDATE_USER_STARTED';
export const UPDATE_USER_SUCCESSED = 'UPDATE_USER_SUCCESSED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
