export const FETCH_USER_STARTED = 'FECT_USER_STARTED';
export const FETCH_USER_SUCCESSED = 'FECT_USER_SUCCESSED';
export const FETCH_USER_FAILED = 'FECT_USER_FAILED';
export const FETCH_CURRENT_USER = 'FECT_USER_CURRENT_USER';

export const UPDATE_USER_STARTED = 'UPDATE_USER_STARTED';
export const UPDATE_USER_SUCCESSED = 'UPDATE_USER_SUCCESSED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const UPDATE_AVATAR_STARTED = 'UPDATE_AVATAR_STARTED';
export const UPDATE_AVATAR_SUCCESSED = 'UPDATE_AVATAR_SUCCESSED';
export const UPDATE_AVATAR_FAILED = 'UPDATE_AVATAR_FAILED';

export const UPDATE_COVER_STARTED = 'UPDATE_COVER_STARTED';
export const UPDATE_COVER_SUCCESSED = 'UPDATE_COVER_SUCCESSED';
export const UPDATE_COVER_FAILED = 'UPDATE_COVER_FAILED';
