export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/1.jpeg",
        username: "Dương Nghĩa Hiệp",
    },
    {
        id: 2,
        profilePicture: "assets/person/2.jpeg",
        username: "Nguyễn Nhan Gia Bảo",
    },
    {
        id: 3,
        profilePicture: "assets/person/3.jpeg",
        username: "Nguyễn Công Chính",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpeg",
        username: "Nguyễn Minh Hiếu",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpeg",
        username: "Huỳnh Nguyễn Vân Anh",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpeg",
        username: "Trần Dương Chí Hiếu",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpeg",
        username: "Trần Đình Thủ",
    },
    {
        id: 8,
        profilePicture: "assets/person/8.jpeg",
        username: "Chính Nguyễn",
    },
    {
        id: 9,
        profilePicture: "assets/person/9.jpeg",
        username: "Hiệp Dương",
    },
    {
        id: 10,
        profilePicture: "assets/person/10.jpeg",
        username: "Hiếu Trần",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Tình yêu dành cho tất cả, hận thù không dành cho ai.",
        photo: "assets/post/1.jpeg",
        date: "5 phút trước",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "assets/post/2.jpeg",
        date: "15 phút trước",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Mỗi khoảnh khắc là một khởi đầu mới.",
        photo: "assets/post/3.jpeg",
        date: "1giờ trước",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "assets/post/4.jpeg",
        date: "4 giờ trước",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "assets/post/5.jpeg",
        date: "5 giờ trước",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "assets/post/6.jpeg",
        date: "1 ngày trước",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Không bao giờ hối tiếc bất cứ điều gì khiến bạn mỉm cười.",
        photo: "assets/post/7.jpeg",
        date: "2 ngày trước",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "assets/post/8.jpeg",
        date: "3 ngày trước",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Thay đổi thế giới bằng cách là chính mình.",
        photo: "assets/post/9.jpeg",
        date: "5 ngày trước",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "assets/post/10.jpeg",
        date: "1 tuần trước",
        userId: 10,
        like: 104,
        comment: 12,
    },
];